#!/bin/bash
set -euo pipefail

# ForceField — hand the file sink to the operating system's log rotator
#
# The three native sinks already rotate under OS management and need nothing from
# you. This script is only about the fourth: `~/.claude/hooks/security.log`, which
# ForceField writes itself and therefore rotates itself, at a hard size ceiling.
#
# What is possible here is not the same on both platforms, and both answers were
# measured rather than assumed:
#
#   Linux   an ordinary user can drive logrotate over their own home with no root
#           anywhere. Measured with logrotate 3.22.0 as uid 1000: rc=0, 196,992
#           bytes rotated to security.log.1, a fresh 0600 file created, state kept
#           in the user's own home. This script prints that config.
#
#   macOS   there is no per-user path at all, and it is not a permissions problem
#           you can work around by owning the file: `newsyslog -f <your-own-conf>`
#           answers `newsyslog: must have root privs` and exits without reading it.
#           The unified log is the natively-rotated sink on macOS; the file sink
#           keeps its own ceiling.
#
# Both numbers below come from log_sinks itself, so this cannot drift from the
# ceiling the code actually enforces.
#
#   scripts/rotation-config.sh            print the config for this platform
#   scripts/rotation-config.sh --install  install it (Linux; user-level, no root)

PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INSTALL=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install) INSTALL=true; shift ;;
    -h | --help)
      sed -n '4,27p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "rotation-config.sh: unknown argument '$1' (try --help)" >&2
      exit 2
      ;;
  esac
done

export FORCEFIELD_HOOKS="$PLUGIN_ROOT/hooks"
eval "$(python3 <<'PY'
import os
import sys

sys.path.insert(0, os.environ["FORCEFIELD_HOOKS"])
import log_sinks

print("MAX_BYTES=%d" % log_sinks.FALLBACK_MAX_BYTES)
print("BACKUP_COUNT=%d" % log_sinks.FALLBACK_BACKUP_COUNT)
print("LOG_PATH=%s" % log_sinks.file_path())
PY
)"

CONF_DIR="$HOME/.config/forcefield"
CONF="$CONF_DIR/logrotate.conf"
STATE="$CONF_DIR/logrotate.state"

emit_logrotate() {
  cat <<EOF
# ForceField security log — generated by scripts/rotation-config.sh
#
# size and rotate mirror log_sinks.FALLBACK_MAX_BYTES / FALLBACK_BACKUP_COUNT, so
# logrotate and ForceField agree on the ceiling instead of racing to a different
# one. ForceField keeps its own in-process rollover either way: that is a hard
# size bound, which a schedule-driven rotator cannot provide, and the two compose
# because ForceField only acts once the file is already over the ceiling.
#
# Run it as yourself — no root, no /etc:
#   logrotate --state $STATE $CONF
# and schedule it with a systemd user timer or a user crontab entry.

$LOG_PATH {
    size $MAX_BYTES
    rotate $BACKUP_COUNT
    create 0600 $(id -un) $(id -gn)
    missingok
    notifempty
    nocompress
    nomail
}
EOF
}

if [[ "$(uname -s)" == "Darwin" ]]; then
  cat >&2 <<EOF
macOS: the file sink cannot be handed to newsyslog, measured rather than assumed.
newsyslog refuses to read a config it was pointed at with -f unless it is running
as root ("newsyslog: must have root privs"), so owning the file changes nothing.

The natively rotated sink on this platform is the unified log, which carries the
whole record including command.line. Measured on this machine: logd rotates it
into 51 sequential ~10 MB .tracev3 segments covering a 45.1 h window.

The file sink keeps its in-process ceiling: $MAX_BYTES bytes x $BACKUP_COUNT backups.
EOF
  exit 0
fi

if ! $INSTALL; then
  emit_logrotate
  exit 0
fi

if ! command -v logrotate >/dev/null 2>&1; then
  echo "rotation-config.sh: logrotate is not installed" >&2
  exit 1
fi

mkdir -p "$CONF_DIR"
emit_logrotate >"$CONF"
chmod 600 "$CONF"
echo "wrote $CONF"
echo
echo "Run it now with:      logrotate --state $STATE $CONF"
echo "Schedule it with a systemd user timer, or a user crontab entry:"
echo "  0 * * * * logrotate --state $STATE $CONF"
